### ISSUE TITLE
Training on a custom dataset possible?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [ValeAri/HEIP#1]
Hello team, thanks for this repo! I was wondering if your model could be trained on a different dataset than you used in your paper - for example the [Colon Nuclei dataset](https://conic-challenge.grand-challenge.org/).
To be brief, this dataset has info about HE images, the segmented nuclei and their classification into 6 types.

Thanks!

**Comment by ValeAri** [comment]
Hello, thank you for the interest for our framework :) . Absolutely! You can train the model with a different dataset with different cell classes.

**Comment by ajinkya-kulkarni** [comment]
Hi, thanks for this info. Is there a preprint or a paper I can have a look at to see the result metrics?

**Comment by ValeAri** [comment]
Hello, I updated the README and I added the link for the preprint version of the article.
